### ISSUE TITLE
Default Nginx page

### ISSUE THREAD

**Issue by CoolestNerdIII** [thecartercenter/elmo#153]
When following the instructions provided for a production setup, when directing to the domain name, the default nginx webpage appears. There are no apparent errors in logs that I have noticed, and I am unsure of any further steps to help resolve the issue. Any help would be greatly appreciated. Thanks! :)

**Comment by hooverlunch** [comment]
Hi there. Can you paste the contents of your nginx.conf file?

**Comment by CoolestNerdIII** [comment]
Sure. I made a gist of it here: 
https://gist.github.com/CoolestNerdIII/dad7d4cbd08c6f52ea5b
Thanks!

**Comment by hooverlunch** [comment]
A couple of thoughts:

   1. Try checking your error log: /var/log/nginx/error.log
   2. There should not be line breaks on line 49. Should be one long line
   of ciphers. This would definitely cause an error.
   3. Have you restarted your server since you installed the config? `sudo
   service nginx restart`.


On Wed, Oct 21, 2015 at 9:48 AM, Paul Wilson <notifications@github.com>
wrote:

> Sure. I made a gist of it here:
> https://gist.github.com/CoolestNerdIII/dad7d4cbd08c6f52ea5b
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thecartercenter/elmo/issues/153#issuecomment-149901604>
> .
>



-- 
Tom Smyth

Worker-Owner, Sassafras Tech Collective
Specializing in innovative, usable tech for social change
sassafras.coop *·* @sassafrastech

Resident, Touchstone Cohousing
touchstonecohousing.org

**Comment by CoolestNerdIII** [comment]
1. In the error.log, the only thing that I have noticed worth noting is this: 

```2015/10/20 22:08:55 [warn] 21472#0: server name "/home/vip/elmo/public" has suspicious s
ymbols in /etc/nginx/nginx.conf:39```

2. Sorry, the line is one long line. There was a small issue when pasting into gist.
3. Yes 

The log looks like the following: 
```
2015/10/20 22:08:55 [warn] 21472#0: server name "/home/vip/elmo/public" has suspicious s
ymbols in /etc/nginx/nginx.conf:39
[ 2015-10-20 22:08:55.1576 21473/7fdde904b7c0 age/Wat/WatchdogMain.cpp:1275 ]: Starting
Passenger watchdog...
[ 2015-10-20 22:08:55.1631 21476/7fab643a57c0 age/Cor/CoreMain.cpp:956 ]: Starting Passe
nger core...
[ 2015-10-20 22:08:55.1714 21476/7fab643a57c0 age/Cor/CoreMain.cpp:233 ]: Passenger core
 running in multi-application mode.
[ 2015-10-20 22:08:55.1728 21476/7fab643a57c0 age/Cor/CoreMain.cpp:706 ]: Passenger core
 online, PID 21476
[ 2015-10-20 22:08:55.1789 21481/7fa47427c7c0 age/Ust/UstRouterMain.cpp:503 ]: Starting
Passenger UstRouter...
[ 2015-10-20 22:08:55.1877 21481/7fa47427c7c0 age/Ust/UstRouterMain.cpp:316 ]: Passenger
 UstRouter online, PID 21481
```

**Comment by md5** [comment]
You're missing a semicolon on the `server_name` line, causing Nginx to ignore your `root` directive.

**Comment by CoolestNerdIII** [comment]
Wow! Thank you so very very much. That fixed it! 

Thank you both @hooverlunch and @md5

**Comment by md5** [comment]
:+1:
