### ISSUE TITLE
API

### ISSUE THREAD

**Issue by thupham17** [thecartercenter/elmo#325]
I'm trying to pull data from the API but it looks like the documentation is outdated since it uses the old cceom.org URL. What is the new host address?

**Comment by thupham17** [comment]
Never mind! I found the host: staging.getelmo.org.

**Comment by workroommedia** [comment]
Hi Thu,
Use the https://staging.getelmo.org address for the testing server.

Dottie

Sent from my iPhone

On May 24, 2017, at 11:06 AM, Thu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi I'm trying to pull data from the API but it looks like the documentation is outdated since it uses the old cceom.org<http://cceom.org> URL. What is the new host address?
