### ISSUE TITLE
Having trouble adding questions to forms and options to option sets

### ISSUE THREAD

**Issue by trycrmr** [thecartercenter/elmo#448]
Between two environments I am having trouble adding questions to forms and options to option sets. I don't typically work with Rails so my best guess is it's something to do with the asset pipeline.  When I click "add option" I do not see any activity on the server-side or the client-side. See the screenshot below. 

![image](https://user-images.githubusercontent.com/6002123/40568216-482ae700-6047-11e8-9c6a-2a5ea7a118fe.png)

Presuming the asset pipeline bundled the client-side correctly I'm not sure what the next step is. The two environments are my local machine and [elmo.edipdev.io](http://elmo.edipdev.io/). Note that the latter is a temporary environment to validate ELMO's capabilities. Thanks in advance for any attention!

**Comment by trycrmr** [comment]
In reviewing this post I have not looked into those client-side errors adequately yet. I assumed no errors on the server-side with the asset pipeline meant these errors were known issues with the tool. If there are any hints as to where to look to resolve those issues they would be very much appreciated!

**Comment by smoyth** [comment]
It looks like there is some problem loading React proptypes. I would bet this is causing _all_ JS to fail for you, not just the Option Set page.

.. ah, it seems you're on React 16 instead of 15. Did you run `bundle update` by chance? The Gemfile.lock has `react-rails` pegged to 2.3.0, which should include React 15. If you do `git reset --hard` and then `bundle install` that should fix it (unless you've committed changes to the `Gemfile.lock`)

**Comment by trycrmr** [comment]
Superb! I will try that and get back to you :-)

**Comment by trycrmr** [comment]
That worked! I hadn't committed the changes so I just needed to unstage them with `git add -- .` Thanks thanks thanks!
